[build]
command = "npx nx run ui:build"
publish = "dist/packages/ui"

[build.environment]
NODE_VERSION = "20"         # or 18, depending on your project
PYTHON_VERSION = "3.11"     # Correct existing stable version
GO_VERSION = "1.19"         # If needed (or remove if not using Go)

[functions]
node_bundler = "esbuild"
