services:
  - type: web
    name: inone-main
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --force; npx nx run services-main:build 
    startCommand: node dist/apps/inone-main/main.js # Correct NestJS startup for production build
    envVars:
      - key: NX_DAEMON
        value: "false"
      - key: PORT
        value: "3005"
      - key: RESPONSE_TIMEOUT
        value: "30"
      - key: CORS_ORIGIN
        value: "*"
      - key: RATE_LIMIT_WINDOW
        value: "900000"
      - key: RATE_LIMIT_MAX
        value: "100"
      - key: DB_HOST
        value: mysql-b96cae4-ummidisettisai01-ebc2.e.aivencloud.com
      - key: DB_PORT
        value: "21240"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: in-one
      - key: EMAIL_USER
        value: saikumarsolo2000@gmail.com
      - key: EMAIL_PASS
        value: bxls csck fyrh cote
      - key: JWT_SECRET
        sync: false # Missing 'sync: false' here originally; must secure this
      - key: ENCRYPTION_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: drjxzdno4
      - key: CLOUDINARY_API_KEY
        value: "335634365556561"
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /health
